### ISSUE TITLE
Numeric IgxInput have spin buttons when editing in Firefox

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular-samples#1724]
### Description 
Browser: Firefox

Editing a cell with numeric igxInput there are spin buttons in Firefox

### Steps to reproduce  

1. https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing.html
2. Edit the first cell in the second column

### Result  
Observe that the input has spin buttons

### Expected result  
The input must not have spin buttons

### Attachments  
![image](https://user-images.githubusercontent.com/37667452/73660378-be525580-46a0-11ea-813e-9f3feb490538.png)

**Comment by simeonoff** [comment]
This is not a bug, it's simply the result of the default browser behavior and the fact that we don't have  a specification for numeric type inputs. The expected result should not be to remove the buttons, rather to come up with a specification and design for numeric type inputs. Also, this issue is not isolated to the angular-samples repository, it's rather a feature-request, which should be logged under the igniteui-angular repo.

**Comment by Lipata** [comment]
https://stackoverflow.com/questions/23372903/hide-spinner-in-input-number-firefox-29
