### ISSUE TITLE
Inputs do not comply with the applied theme

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#1757]
### Description  
When a new theme is applied from the theming service, the inputs are not changed based on the theme. For example, if you choose Bootstrap theme or Fluent theme, the inputs will stay Material, we should add `type` attribute to all input elements based on the selected theme `type="bootstrap"` and `type="fluent"`

<staging environment>/products/ignite-ui-angular/angular/components/input_group.html

**Comment by MayaKirova** [comment]
@zdrawku @simeonoff Should this be applied to inputs that are rendered post initialization - like grid editors when you enter edit mode for example?

**Comment by MayaKirova** [comment]
@zdrawku Also do you mean the type attribute of the DOM input elements, or perhaps the type property of the actual component - https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/input-group/input-group.component.ts#L191

**Comment by simeonoff** [comment]
@MayaKirova Ideally, yes. We should be switching this based on the theme. However, I don't know exactly how we can implement this since we cannot rely on a specific CSS class being applied. This is a shortcoming of how the inputs were initially architected, with no other theme than material in mind. Back then the `type` input made sense, now I reckon it calls for some other approach.

**Comment by MayaKirova** [comment]
@ChronosSF @simeonoff  @zdrawku Perhaps it could  be implemented similarly to the DisplayDensity so that it can be set globally on the application level or on individual component so their respective children can inherit the correct value. We could set the [`type` ](https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/input-group/input-group.component.ts#L191) based on  what is selected in the theming-widget for the samples, however with the current implementation we would have to set it individually to each control that happens to use an input-group internally (like combo,time-picker etc.). Components that create some inputs runtime (like grid for editing, filtering etc.) ,may also be a problem since we don't have direct access to them (unless we template our own editors).

**Comment by ChronosSF** [comment]
Requires further fixes for Stackblitz
