### ISSUE TITLE
Keyboard navigation sample issues

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular-samples#2038]
### Description  

1. The action hints are not contextual to the type of element that is currently selected. 

For example, when group row or details row is selected `Enter` is not valid option as group row and detail row is not editable, so if the user hits `Enter` nothing will happen.

Same for header multi-column header cells and normal data header cells.
For mch header cells options for showing filters are displayed but they don't allow showing a filter.
For normal header cells options for expand/collapsed are listed but they are not expandable.

2. There is no need to have a separate action for expand/collapse group row as it uses the same key combinations as the master-detail row.  Both can be combined and summarized (expand/collapses row) and shown for expandable rows (master-detail row, group row, hierarchical row etc.).

3. There is a typo - "master datils" in alt+ arrow keys description should be "master details".

**Comment by Aleksandyr** [comment]
@MayaKirova I see your point but the goal of the sample wasn't this.
It has been decided that we are going to track only which section of the grid we have focused (thead, tbody, tfooter, etc.) and based on the section we will list the commands.
So once you reached or somehow executed the command it will complete otherwise it won't.

The other thing that concerns me is the logic the sample already has, it's more than 300 lines of code so let's not make it so much complex. 

I do agree that we have a type and I will fix it, but for now, we won't go with the changes you have requested. I do agree that the sample would look better, but that wasn't the context then.

**Comment by MayaKirova** [comment]
@Aleksandyr 
I don't think the sample's complexity is an issue as it does not seem like something a user would need to implement in their own application and is rather a 'tutorial' of how navigation works. 
As such having it show the available actions based on the context would be more useful to the user than showing all actions and having the user figure out where the activation needs to be in order to complete the action.

@zdrawku Let me know what you think. Perhaps the sample can be improved in future versions.

**Comment by Aleksandyr** [comment]
@MayaKirova If that's the case we can extend it. I will make an arrangement and we can discuss that with either @DaniMarinov or @StefanIvanov. 
I agree that it's not about the logic but more as a tutorial.
