### ISSUE TITLE
Toolbar custom theming

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular-samples#2362]
### Description  
Toolbar custom theming is not applied on the pining/hiding menus

### Steps to reproduce  

Steps to reproduce
1. Open: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/toolbar#demo

2. Open pinning or hiding menu

![image](https://user-images.githubusercontent.com/52001020/99547891-bca01700-29c0-11eb-8524-b0076ea6f7d8.png)

**Comment by desig9stein** [comment]
That whole element is a separate component, which can only be used with the toolbar component. The styling of this component is not part of the toolbar component. Since this does not use either the dropdown or the combo, I assume that we should add the styling for it inside the toolbar topic. Another option will be to create a separate topic, but in my opinion, it will be weird, since it cant be used outside of the toolbar.
@simeonoff @radomirchev let me know what you guys think is the appropriate approach here.

**Comment by simeonoff** [comment]
Does that component have a theme? If yes, then ok - the styling should be a part of the toolbar topic.

**Comment by desig9stein** [comment]
@simeonoff Yes, it has a theme. I will update the toolbar topic.
