### ISSUE TITLE
Search and Text Highlight not highlighting matches

### ISSUE THREAD

**Issue by igdmdimitrov** [IgniteUI/igniteui-angular-samples#2638]
### Description  
Search and Text Highlight are not highlighting any text on match

### Steps to reproduce  
1. Open any of the following links

[https://staging.infragistics.com/products/ignite-ui-angular/angular/components/texthighlight](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/texthighlight) - change theme to dark

[https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/search](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/search)

[https://staging.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/search](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/search)

2. Enter some valid text (that will match) in the search inputs

### Result  
Text highlight is not highlighting matches on dark themes
Grid/TreeGrid Search matches are not highlighted on any theme

### Expected result  
Text/Search matches should be highlighted (on light and dark themes)

**Comment by desig9stein** [comment]
@igdmdimitrov I am unable to reproduce this in the vNext branch in igniteui-angular-samples. I believe that the staging is not up to date and this is already fixed.

**Comment by gedinakova** [comment]
This seems to be tightly coupled with the theming. The highlight works until the first theme change. Once a theme is selected in "Change theme" widget, the highlight style breaks because it can't resolve the CSS variables.
![image](https://user-images.githubusercontent.com/16817847/116225647-c5a8c780-a75a-11eb-89de-14390977ce4b.png)

@ChronosSF Could you, please, have a look at this?
