### ISSUE TITLE
Grid Excel Style Filtering Operations sample

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular-samples#2887]
### Steps to reproduce  

1. Go to Grid Excel Style Filtering Operations sample
2. Hide All columns

### Result  
Still, there are visible columns:
![bug4](https://user-images.githubusercontent.com/14248932/143002838-e76df903-0267-49c6-887a-48a8570e5dbe.PNG)

Same applies for Grid Column Hiding sample:
![bug5](https://user-images.githubusercontent.com/14248932/143002917-b952ac1e-da70-4ac0-ba2e-81479a39dac9.PNG)

**Comment by teodosiah** [comment]
@hanastasov both columns - 'Quantity Per Unit' and 'ContactTitle' are not hidden because their property disableHiding is set to 'true'.

Grid Excel Style Filtering Operations sample:
![image](https://user-images.githubusercontent.com/52423497/184814249-4b858c36-074b-4b56-adcc-42c9a223500c.png)

Grid Column Hiding sample:
![image](https://user-images.githubusercontent.com/52423497/184814331-0f624a5d-c0b3-47d5-bba6-524b908ba929.png)
