### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-angular-samples#319]
### Description  
Samples do no work in IE 11 correctly.

### Bugs

- [x] “Unable to get property 'replace' of undefined or null reference” console error flickers on all of the samples.

![excel-exporter-1](https://user-images.githubusercontent.com/6439482/39803708-7bebbd5a-537a-11e8-9d03-e0e0bdca0f6f.PNG)

~~Grid’s width is smaller than expected in all samples containing a grid~~ (logged as a separate issue https://github.com/IgniteUI/igniteui-angular/issues/1330)

![excel-exporter-2](https://user-images.githubusercontent.com/6439482/39803847-01b29120-537b-11e8-8307-d1002cb09dba.PNG)

XSS error in the following samples
- [x] Card Demo
- [x] Ripple Demo
- [x] Input Group Styling
- [x] Button Demo

![capture](https://user-images.githubusercontent.com/6439482/39803872-195092d2-537b-11e8-93e7-f2b952c9ced5.PNG)

**Comment by tiliev** [comment]
@kdinev, @SlavUI, @zdrawku, @ig-ealbert, @pnishimura
The first issue from the list affects all of our samples and currently we do not support StackBlitz samples in IE 11.
The guys from StackBlitz confirmed IE 11 is having an issue with compiling our Sass (as seen from the attached issue). I'll perform a little bit more research to be sure we can't proceed with using Sass. 
What we'll do after that is to compile all the Sass to CSS server-side specifically for StackBlitz + IE 11. I'll keep in touch.

**Comment by gmurray81** [comment]
Careful. When Mike and I were looking at this, it seemed one of the largest load time factors was whether you were loading directly from the POST API, or whether you had forked and saved the sample first. More caching and bundling seems to be done for a user owned sample rather than a sample generated from the API so make sure not to test something directly created by the API vs something that you've modified and saved. Lots of red herrings.

I think we may want to change the sample generation process potentially so that the build updates a set of named samples and saves them (if possible with the API) in stackblitz rather than to use the POST API.

I know Mike submitted a bug report to Stackblitz RE the POST API issue too.

**Comment by tiliev** [comment]
The issue with grid width is logged separately because it is not connected with the live editing - https://github.com/IgniteUI/igniteui-angular/issues/1330.
