### ISSUE TITLE
Flickering of the search UI in the Business propeller sample

### ISSUE THREAD

**Issue by rmkrmk** [IgniteUI/igniteui-angular-samples#373]
### Description  
The whole search UI is flickering when pressing the "find previous" and "find next" buttons in the search field of the Business propeller sample.

### Steps to reproduce  

1. Open the following sample:
https://staging.infragistics.local/products/ignite-ui-angular
2. Type something in the search field at the top (for example "ai")
3. Start clicking on the find next button

### Result  
The search UI elements (the X button, the search criteria and the number of results) are all flickering on each button click.

### Expected result  
The search UI should not be flickering.

**Comment by desig9stein** [comment]
@rmkrmk this happens because when you click on the button you lose the focus from the input and when you lose the focus the class "igx-input-group-focused" which gives the white background is removed.

We can add some extra class to the input when its clicked and remove that class only if the user clicks outside of the input. In that way, we can add the white background when we have that class and not use the focus one
