### ISSUE TITLE
Loading of production angular components samples 'hangs' occasionally on Edge

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#43]
### Description  
The page is not loaded on Edge every time, Ctrl + F5 refresh is needed. Maybe this is somehow related to the Iframe element which is loading the Samples links in DocFX project.

### Steps to reproduce  

Open Edge browser and load our official demos page:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/tabbar.html

### Result  
No samples are loaded

### Expected result  
Samples should be loaded

### Attachments  

![image](https://user-images.githubusercontent.com/11193764/35671269-8939a39c-0743-11e8-82d3-56731b7426c7.png)

**Comment by tiliev** [comment]
The issue is caused by a CSS class which is applied to each iframe in our documentation (the class shows the loading circle and hides the iframe contents). Since the script which does that is loaded at the end of the page sometimes the class is applied after the iframe is loaded and it is never removed. The entire script "docfx.js" should be loaded in the <head>, before any iframe is rendered.

**Comment by tiliev** [comment]
Duplicate to https://github.com/IgniteUI/igniteui-docfx/issues/93.
