### ISSUE TITLE
Filtering dropdown on date column changes its width 

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular-samples#488]
### Description  
Filtering dropdown on date column changes its width when applying certain date filter

### Steps to reproduce  

1. Navigate to Filtering sample on staging
2. Open the date column filter dropdown
3. Select some date

### Result  
Filtering dropdown becomes wider

### Expected result  
Filtering dropdown width doesn't change

**Comment by zdrawku** [comment]
@sboykova @sstoyanovIG this is probably a bug in our code, could you take a look

**Comment by sstoyanovIG** [comment]
The issue is not related with filtering itself, because in the Editing sample (https://staging.infragistics.local/products/ignite-ui-angular/angular/components/grid_editing.html) if you edit Order Date column the same behavior occurs. I believe the issue is related with Dialog and Overlay that the DatePikcer uses. Related issue IgniteUI/igniteui-angular#1793
