### ISSUE TITLE
Add lazy loading to all samples routes

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#776]
### Description  
Curently only Excel library samples have `lazy loading`.
[Lazy loading](https://github.com/IgniteUI/igniteui-angular-samples/blob/9ed0f37594e03829b4cf2683caad19dddaa32751/src/app/app-routing.module.ts#L345) should be implemented for all samples

## Bundles
- [x] **Grid CRM** bundle - in progress Hristo
- [x] **Charts** bundle - (https://github.com/IgniteUI/igniteui-angular-samples/pull/868)
- [x] **Gauges** bundle (https://github.com/IgniteUI/igniteui-angular-samples/pull/861)
- [x] **Excel library** bundle (https://github.com/IgniteUI/igniteui-angular-samples/pull/869)
- [x] **IgxGrid** bundle - in progress Hristo
- [x] **IgxTreeGrid** bundle  -(https://github.com/IgniteUI/igniteui-angular-samples/pull/877)
- [x] **Lists** bundle - List View + Combo(https://github.com/IgniteUI/igniteui-angular-samples/pull/867)
- [x] **Styling and themes** bundle (https://github.com/IgniteUI/igniteui-angular-samples/pull/866)
- [x] **Data Entries** bundle - (https://github.com/IgniteUI/igniteui-angular-samples/pull/878)
- [x] **Data Display** bundle - (https://github.com/IgniteUI/igniteui-angular-samples/pull/878)
- [x] **Interactions** bundle (https://github.com/IgniteUI/igniteui-angular-samples/pull/859)
- [x] **Menus** bundle (https://github.com/IgniteUI/igniteui-angular-samples/pull/865)
- [x] **Layouts** bundle (https://github.com/IgniteUI/igniteui-angular-samples/pull/874) 
- [x] **Notifications** bundle (https://github.com/IgniteUI/igniteui-angular-samples/pull/857)
- [x] **Scheduling** bundle (https://github.com/IgniteUI/igniteui-angular-samples/pull/863)
- [x] **Services** bundle (https://github.com/IgniteUI/igniteui-angular-samples/pull/875)

**Comment by tiliev** [comment]
We should separate the sample into different modules. The lazy loading will create a `.js` file per each module. These `.js` files will be loaded only if a sample in the module is accessed.
The following bundles could be created:
- **Grid CRM** bundle - holding only one sample. This is because we use it on our main page (https://www.infragistics.com/products/ignite-ui-angular) and we need the best performance possible.
- **Charts** bundle
- **Gauges** bundle
- **Excel library** bundle - currently we have a bundle for each excel library sample, but I suggest we do only one
- **Grids** bundle - Data Grid + TreeGrid
- **Lists** bundle - List View + Combo
- **Styling and themes** bundle
- **Data Entry & Display** bundle
- **Interactions** bundle
- **Menus** bundle
- **Layouts** bundle
- **Notifications** bundle
- **Scheduling** bundle
- **Services** bundle
