### ISSUE TITLE
Stackblitz configuration: The dependencies for this project couldn't be resolved

### ISSUE THREAD

**Issue by lalo-mx** [IgniteUI/igniteui-angular-samples#782]
### Description  
Could not open samples on StackBlitz

### Steps to reproduce  

1. Open StackBlitz import page for samples https://stackblitz.com/github/IgniteUI/igniteui-angular-samples/.
2. An error is shown: The dependencies for this project couldn't be resolved.

### Result  
An error: The dependencies for this project couldn't be resolved.

### Expected result  
The samples run and be displayed.

### Attachments  
![image](https://user-images.githubusercontent.com/7459881/49382934-3d36b180-f6dd-11e8-978b-119574dec98d.png)

**Comment by tiliev** [comment]
@lalo-mx, currently StackBlitz has some issues with caching npm package versions (https://github.com/stackblitz/core/issues/624). This is why the dependencies cannot be resolved.
Each sample from this repo can be found in our documentation - https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html, where it is optimized, tested and runnable in StackBlitz. Just use the `View on StackBlitz` buttons. We strongly recommend this approach instead of importing the whole project.

**Comment by lalo-mx** [comment]
The documentation is usually useful but is not up to date as fast as the releases.  The StackBlitz is a fast way of testing the new features and fixes.

**Comment by zdrawku** [comment]
Also, you can use the [angular-samples](https://github.com/IgniteUI/igniteui-angular-samples/releases) versions that we tag, we are going to update them regularly based on the included new samples and version updates.


Steps to execute:
1. Download the package 
2. `npm i`

3. `npm run start`
