### ISSUE TITLE
Badges component not working

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#934]
### Description  
Logged from @@luiscla27 https://github.com/IgniteUI/igniteui-angular/issues/3830

Describe the issue.

 * igniteui-angular version: `7.1.2` and `7.2.0-beta.1`
 * browser: Chrome

### Steps to reproduce  

1. Go to your demo page 
2. https://www.infragistics.com/products/ignite-ui-angular/angular/components/badge.html

### Result  
You'll see that the badges are missing

### Expected result  
Badges should work showing correctly the three badge-type "warning", "error" and "success"

### Attachments  
![igx-badge-missing](https://user-images.githubusercontent.com/29953012/52312263-9508c780-296f-11e9-9c4c-b8212244fa43.gif)

**Comment by luiscla27** [comment]
Thank you @zdrawku, btw i think the correct position [here](https://github.com/IgniteUI/igniteui-angular-samples/blob/8c45c6c4baa43ce801839051747ec26b813e0427/src/app/data-display/badge/badge-sample-3/badge-sample-3.component.scss#L13) is `relative` instead of `absolute` so it wouldn't break when the badge is scroll up/down :)
